import React, {useState, useEffect, useCallback} from "react";

import Input from "../shared/input";
import Dropdown from "../shared/dropdown";
import PrevIcon from "../../assets/icon/prev-green.svg";
import NextIcon from "../../assets/icon/next-white.svg";

const Address = ({ setForm, formData, navigation }) => {
  const { address, city, state, postalCode, country } = formData;
  const { previous, next } = navigation;
  const [isDisabled, setDisabled] = useState(true);
  const states = [
      ["AL","Alabama"],
      ["AK","Alaska"],
      ["AZ","Arizona"],
      ["AR","Arkansas"],
      ["CA","California"],
      ["CO","Colorado"],
      ["CT","Connecticut"],
      ["DE","Delaware"],
      ["DC","District of Columbia"],
      ["FL","Florida"],
      ["GA","Georgia"],
      ["GU","Guam"],
      ["HI","Hawaii"],
      ["ID","Idaho"],
      ["IL","Illinois"],
      ["IN","Indiana"],
      ["IA","Iowa"],
      ["KS","Kansas"],
      ["KY","Kentucky"],
      ["LA","Louisiana"],
      ["ME","Maine"],
      ["MD","Maryland"],
      ["MA","Massachusetts"],
      ["MI","Michigan"],
      ["MN","Minnesota"],
      ["MS","Mississippi"],
      ["MO","Missouri"],
      ["MT","Montana"],
      ["NE","Nebraska"],
      ["NV","Nevada"],
      ["NH","New Hampshire"],
      ["NJ","New Jersey"],
      ["NM","New Mexico"],
      ["NY","New York"],
      ["NC","North Carolina"],
      ["ND","North Dakota"],
      ["MP","Northern Marina Islands"],
      ["OH","Ohio"],
      ["OK","Oklahoma"],
      ["OR","Oregon"],
      ["PA","Pennsylvania"],
      ["RI","Rhode Island"],
      ["SC","South Carolina"],
      ["SD","South Dakota"],
      ["TN","Tennessee"],
      ["TX","Texas"],
      ["AA","U.S. Armed Forces - Americas"],
      ["AE","U.S. Armed Forces - Europe"],
      ["AP","U.S. Armed Forces - Pacific"],
      ["xx","Unknown State"],
      ["UT","Utah"],
      ["VT","Vermont"],
      ["VI","Virgin Islands, U.S."],
      ["VA","Virginia"],
      ["WA","Washington"],
      ["WV","West Virginia"],
      ["WI","Wisconsin"],
      ["WY","Wyoming"],
      ["AB","Alberta"],
      ["BC","British Columbia"],
      ["MB","Manitoba"],
      ["NB","New Brunswick"],
      ["NL","Newfoundland"],
      ["NT","Northwest Territories"],
      ["NS","Nova Scotia"],
      ["NU","Nunavut"],
      ["ON","Ontario"],
      ["PE","Prince Edward Island"],
      ["QC","Quebec"],
      ["SK","Saskatchewan"],
      ["YT","Yukon"],
      ["ACT","Australian Capital Territory"],
      ["NSW","New South Wales"],
      ["NT","Northern Territory"],
      ["QLD","Queensland"],
      ["SA","South Australia"],
      ["TAS","Tasmania"],
      ["VIC","Victoria"],
      ["WA","Western Australia"]
  ];
  const countries = [
      ["UNITED STATES", "UNITED STATES"],
      ["CANADA", "CANADA"],
      ["UNITED KINGDOM", "UNITED KINGDOM"],
      ["RUSSIAN FEDERATION", "RUSSIAN FEDERATION"],
      ["CHINA", "CHINA"],
      ["JAPAN", "JAPAN"],
      ["KOREA, REPUBLIC OF", "KOREA, REPUBLIC OF"],
      ["KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"],
      ["MEXICO", "MEXICO"],
      ["GERMANY", "GERMANY"],
      ["SPAIN", "SPAIN"],
      ["FRANCE", "FRANCE"],
      ["FINLAND", "FINLAND"],
      ["ICELAND", "ICELAND"],
      ["AUSTRALIA", "AUSTRALIA"],
      ["AFGHANISTAN", "AFGHANISTAN"],
      ["ALAND ISLANDS", "ALAND ISLANDS"],
      ["ALBANIA", "ALBANIA"],
      ["ALGERIA", "ALGERIA"],
      ["AMERICAN SAMOA", "AMERICAN SAMOA"],
      ["ANDORRA", "ANDORRA"],
      ["ANGOLA", "ANGOLA"],
      ["ANGUILLA", "ANGUILLA"],
      ["ANTARCTICA", "ANTARCTICA"],
      ["ANTIGUA AND BARBUDA", "ANTIGUA AND BARBUDA"],
      ["ARGENTINA", "ARGENTINA"],
      ["ARMENIA", "ARMENIA"],
      ["ARUBA", "ARUBA"],
      ["AUSTRIA", "AUSTRIA"],
      ["AZERBAIJAN", "AZERBAIJAN"],
      ["BAHAMAS", "BAHAMAS"],
      ["BAHRAIN", "BAHRAIN"],
      ["BANGLADESH", "BANGLADESH"],
      ["BARBADOS", "BARBADOS"],
      ["BELARUS", "BELARUS"],
      ["BELGIUM", "BELGIUM"],
      ["BELIZE", "BELIZE"],
      ["BENIN", "BENIN"],
      ["BERMUDA", "BERMUDA"],
      ["BHUTAN", "BHUTAN"],
      ["BOLIVIA", "BOLIVIA"],
      ["BOSNIA AND HERZEGOVINA", "BOSNIA AND HERZEGOVINA"],
      ["BOTSWANA", "BOTSWANA"],
      ["BOUVET ISLAND", "BOUVET ISLAND"],
      ["BRAZIL", "BRAZIL"],
      ["BRITISH INDIAN OCEAN TERRITORY", "BRITISH INDIAN OCEAN TERRITORY"],
      ["BRUNEI DARUSSALAM", "BRUNEI DARUSSALAM"],
      ["BULGARIA", "BULGARIA"],
      ["BURKINA FASO", "BURKINA FASO"],
      ["BURUNDI", "BURUNDI"],
      ["CAMBODIA", "CAMBODIA"],
      ["CAMEROON", "CAMEROON"],
      ["CAPE VERDE", "CAPE VERDE"],
      ["CAYMAN ISLANDS", "CAYMAN ISLANDS"],
      ["CENTRAL AFRICAN REPUBLIC", "CENTRAL AFRICAN REPUBLIC"],
      ["CHAD", "CHAD"],
      ["CHILE", "CHILE"],
      ["CHRISTMAS ISLAND", "CHRISTMAS ISLAND"],
      ["COCOS (KEELING) ISLANDS", "COCOS (KEELING) ISLANDS"],
      ["COLOMBIA", "COLOMBIA"],
      ["COMOROS", "COMOROS"],
      ["CONGO", "CONGO"],
      ["CONGO, THE DEMOCRATIC REPUBLIC OF THE", "CONGO, THE DEMOCRATIC REPUBLIC OF THE"],
      ["COOK ISLANDS", "COOK ISLANDS"],
      ["COSTA RICA", "COSTA RICA"],
      ["COTE D'IVOIRE", "COTE D'IVOIRE"],
      ["CROATIA", "CROATIA"],
      ["CUBA", "CUBA"],
      ["CYPRUS", "CYPRUS"],
      ["CZECH REPUBLIC", "CZECH REPUBLIC"],
      ["DENMARK", "DENMARK"],
      ["DJIBOUTI", "DJIBOUTI"],
      ["DOMINICA", "DOMINICA"],
      ["DOMINICAN REPUBLIC", "DOMINICAN REPUBLIC"],
      ["ECUADOR", "ECUADOR"],
      ["EGYPT", "EGYPT"],
      ["EL SALVADOR", "EL SALVADOR"],
      ["EQUATORIAL GUINEA", "EQUATORIAL GUINEA"],
      ["ERITREA", "ERITREA"],
      ["ESTONIA", "ESTONIA"],
      ["ETHIOPIA", "ETHIOPIA"],
      ["FALKLAND ISLANDS (MALVINAS)", "FALKLAND ISLANDS (MALVINAS)"],
      ["FAROE ISLANDS", "FAROE ISLANDS"],
      ["FIJI", "FIJI"],
      ["FRENCH GUIANA", "FRENCH GUIANA"],
      ["FRENCH POLYNESIA", "FRENCH POLYNESIA"],
      ["FRENCH SOUTHERN TERRITORIES", "FRENCH SOUTHERN TERRITORIES"],
      ["GABON", "GABON"],
      ["GAMBIA", "GAMBIA"],
      ["GEORGIA", "GEORGIA"],
      ["GHANA", "GHANA"],
      ["GIBRALTAR", "GIBRALTAR"],
      ["GREECE", "GREECE"],
      ["GREENLAND", "GREENLAND"],
      ["GRENADA", "GRENADA"],
      ["GUADELOUPE", "GUADELOUPE"],
      ["GUAM", "GUAM"],
      ["GUATEMALA", "GUATEMALA"],
      ["GUERNSEY", "GUERNSEY"],
      ["GUINEA", "GUINEA"],
      ["GUINEA-BISSAU", "GUINEA-BISSAU"],
      ["GUYANA", "GUYANA"],
      ["HAITI", "HAITI"],
      ["HEARD ISLAND AND MCDONALD ISLANDS", "HEARD ISLAND AND MCDONALD ISLANDS"],
      ["HOLY SEE (VATICAN CITY STATE)", "HOLY SEE (VATICAN CITY STATE)"],
      ["HONDURAS", "HONDURAS"],
      ["HONG KONG", "HONG KONG"],
      ["HUNGARY", "HUNGARY"],
      ["INDIA", "INDIA"],
      ["INDONESIA", "INDONESIA"],
      ["IRAN, ISLAMIC REPUBLIC OF", "IRAN, ISLAMIC REPUBLIC OF"],
      ["IRAQ", "IRAQ"],
      ["IRELAND", "IRELAND"],
      ["ISLE OF MAN", "ISLE OF MAN"],
      ["ISRAEL", "ISRAEL"],
      ["ITALY", "ITALY"],
      ["JAMAICA", "JAMAICA"],
      ["JERSEY", "JERSEY"],
      ["JORDAN", "JORDAN"],
      ["KAZAKHSTAN", "KAZAKHSTAN"],
      ["KENYA", "KENYA"],
      ["KIRIBATI", "KIRIBATI"],
      ["KUWAIT", "KUWAIT"],
      ["KYRGYZSTAN", "KYRGYZSTAN"],
      ["LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LAO PEOPLE'S DEMOCRATIC REPUBLIC"],
      ["LATVIA", "LATVIA"],
      ["LEBANON", "LEBANON"],
      ["LESOTHO", "LESOTHO"],
      ["LIBERIA", "LIBERIA"],
      ["LIBYAN ARAB JAMAHIRIYA", "LIBYAN ARAB JAMAHIRIYA"],
      ["LIECHTENSTEIN", "LIECHTENSTEIN"],
      ["LITHUANIA", "LITHUANIA"],
      ["LUXEMBOURG", "LUXEMBOURG"],
      ["MACAO", "MACAO"],
      ["MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"],
      ["MADAGASCAR", "MADAGASCAR"],
      ["MALAWI", "MALAWI"],
      ["MALAYSIA", "MALAYSIA"],
      ["MALDIVES", "MALDIVES"],
      ["MALI", "MALI"],
      ["MALTA", "MALTA"],
      ["MARSHALL ISLANDS", "MARSHALL ISLANDS"],
      ["MARTINIQUE", "MARTINIQUE"],
      ["MAURITANIA", "MAURITANIA"],
      ["MAURITIUS", "MAURITIUS"],
      ["MAYOTTE", "MAYOTTE"],
      ["MICRONESIA, FEDERATED STATES OF", "MICRONESIA, FEDERATED STATES OF"],
      ["MOLDOVA, REPUBLIC OF", "MOLDOVA, REPUBLIC OF"],
      ["MONACO", "MONACO"],
      ["MONGOLIA", "MONGOLIA"],
      ["MONTSERRAT", "MONTSERRAT"],
      ["MOROCCO", "MOROCCO"],
      ["MOZAMBIQUE", "MOZAMBIQUE"],
      ["MYANMAR", "MYANMAR"],
      ["NAMIBIA", "NAMIBIA"],
      ["NAURU", "NAURU"],
      ["NEPAL", "NEPAL"],
      ["NETHERLANDS", "NETHERLANDS"],
      ["NETHERLANDS ANTILLES", "NETHERLANDS ANTILLES"],
      ["NEW CALEDONIA", "NEW CALEDONIA"],
      ["NEW ZEALAND", "NEW ZEALAND"],
      ["NICARAGUA", "NICARAGUA"],
      ["NIGER", "NIGER"],
      ["NIGERIA", "NIGERIA"],
      ["NIUE", "NIUE"],
      ["NORFOLK ISLAND", "NORFOLK ISLAND"],
      ["NORTHERN MARIANA ISLANDS", "NORTHERN MARIANA ISLANDS"],
      ["NORWAY", "NORWAY"],
      ["OMAN", "OMAN"],
      ["PAKISTAN", "PAKISTAN"],
      ["PALAU", "PALAU"],
      ["PALESTINIAN TERRITORY, OCCUPIED", "PALESTINIAN TERRITORY, OCCUPIED"],
      ["PANAMA", "PANAMA"],
      ["PAPUA NEW GUINEA", "PAPUA NEW GUINEA"],
      ["PARAGUAY", "PARAGUAY"],
      ["PERU", "PERU"],
      ["PHILIPPINES", "PHILIPPINES"],
      ["PITCAIRN", "PITCAIRN"],
      ["POLAND", "POLAND"],
      ["PORTUGAL", "PORTUGAL"],
      ["PUERTO RICO", "PUERTO RICO"],
      ["QATAR", "QATAR"],
      ["REUNION", "REUNION"],
      ["ROMANIA", "ROMANIA"],
      ["RWANDA", "RWANDA"],
      ["SAINT HELENA", "SAINT HELENA"],
      ["SAINT KITTS AND NEVIS", "SAINT KITTS AND NEVIS"],
      ["SAINT LUCIA", "SAINT LUCIA"],
      ["SAINT PIERRE AND MIQUELON", "SAINT PIERRE AND MIQUELON"],
      ["SAINT VINCENT AND THE GRENADINES", "SAINT VINCENT AND THE GRENADINES"],
      ["SAMOA", "SAMOA"],
      ["SAN MARINO", "SAN MARINO"],
      ["SAO TOME AND PRINCIPE", "SAO TOME AND PRINCIPE"],
      ["SAUDI ARABIA", "SAUDI ARABIA"],
      ["SENEGAL", "SENEGAL"],
      ["SERBIA AND MONTENEGRO", "SERBIA AND MONTENEGRO"],
      ["SEYCHELLES", "SEYCHELLES"],
      ["SIERRA LEONE", "SIERRA LEONE"],
      ["SINGAPORE", "SINGAPORE"],
      ["SLOVAKIA", "SLOVAKIA"],
      ["SLOVENIA", "SLOVENIA"],
      ["SOLOMON ISLANDS", "SOLOMON ISLANDS"],
      ["SOMALIA", "SOMALIA"],
      ["SOUTH AFRICA", "SOUTH AFRICA"],
      ["SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"],
      ["SRI LANKA", "SRI LANKA"],
      ["SUDAN", "SUDAN"],
      ["SURINAME", "SURINAME"],
      ["SVALBARD AND JAN MAYEN", "SVALBARD AND JAN MAYEN"],
      ["SWAZILAND", "SWAZILAND"],
      ["SWEDEN", "SWEDEN"],
      ["SWITZERLAND", "SWITZERLAND"],
      ["SYRIAN ARAB REPUBLIC", "SYRIAN ARAB REPUBLIC"],
      ["TAIWAN, PROVINCE OF CHINA", "TAIWAN, PROVINCE OF CHINA"],
      ["TAJIKISTAN", "TAJIKISTAN"],
      ["TANZANIA, UNITED REPUBLIC OF", "TANZANIA, UNITED REPUBLIC OF"],
      ["THAILAND", "THAILAND"],
      ["TIMOR-LESTE", "TIMOR-LESTE"],
      ["TOGO", "TOGO"],
      ["TOKELAU", "TOKELAU"],
      ["TONGA", "TONGA"],
      ["TRINIDAD AND TOBAGO", "TRINIDAD AND TOBAGO"],
      ["TUNISIA", "TUNISIA"],
      ["TURKEY", "TURKEY"],
      ["TURKMENISTAN", "TURKMENISTAN"],
      ["TURKS AND CAICOS ISLANDS", "TURKS AND CAICOS ISLANDS"],
      ["TUVALU", "TUVALU"],
      ["UGANDA", "UGANDA"],
      ["UKRAINE", "UKRAINE"],
      ["UNITED ARAB EMIRATES", "UNITED ARAB EMIRATES"],
      ["UNITED STATES MINOR OUTLYING ISLANDS", "UNITED STATES MINOR OUTLYING ISLANDS"],
      ["URUGUAY", "URUGUAY"],
      ["UZBEKISTAN", "UZBEKISTAN"],
      ["VANUATU", "VANUATU"],
      ["VENEZUELA", "VENEZUELA"],
      ["VIET NAM", "VIET NAM"],
      ["VIRGIN ISLANDS, BRITISH", "VIRGIN ISLANDS, BRITISH"],
      ["VIRGIN ISLANDS, U.S.", "VIRGIN ISLANDS, U.S."],
      ["WALLIS AND FUTUNA", "WALLIS AND FUTUNA"],
      ["WESTERN SAHARA", "WESTERN SAHARA"],
      ["YEMEN", "YEMEN"],
      ["ZAMBIA", "ZAMBIA"],
      ["ZIMBABWE", "ZIMBABWE"],
      ["SOUTH SUDAN", "SOUTH SUDAN"],
  ]

  const validation = useCallback(() => {
    address && city && state && postalCode && country ? setDisabled(false) : setDisabled(true);
  }, [address, city, state, postalCode, country])

  useEffect(() => {
    validation();
  }, [validation])

  return (
    <div className="form">
      <h4>Shipping Address</h4>
      <Input
        label="Address"
        name="address"
        type="text"
        value={address}
        onChange={setForm}
      />
      <Input label="City" name="city" type="text" value={city} onChange={setForm} />
      <Dropdown label="State" name="state" value={state} options={states} onChange={setForm} />
      <Input label="Postal Code" name="postalCode" type="text" value={postalCode} onChange={setForm} />
      <Dropdown label="Country" name="country" value={country} options={countries} onChange={setForm} />
      <div className="d-flex align-items-center justify-content-end nav">
        <button className="prev mr-5" onClick={previous}><img src={PrevIcon} alt="" /> <span>Previous Step</span></button>
        <button className="next" onClick={next} disabled={isDisabled}><span>Next Step</span> <img src={NextIcon} alt="" /></button>
      </div>
    </div>
  );
};

export default Address;