// Auth
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const VERIFY = 'VERIFY';
export const RESEND = 'RESEND';

export const FORGOTPASSWORD = 'FORGOTPASSWORD';
export const CONFIRMFORGOTPASSWORD = 'CONFIRMFORGOTPASSWORD';

export const GETCOUNTRIES = 'GETCOUNTRIES';
export const GETSTATES = 'GETSTATES';

// Account
export const GETACCOUNT = 'GETACCOUNT';
export const GETFISHBOWLACCOUNT = 'GETFISHBOWLACCOUNT';
export const PUTACCOUNT = 'PUTACCOUNT';
export const GETORDERS = 'GETORDERS';
export const CHANGEPASSWORD = 'CHANGEPASSWORD';
export const ERROROLDPASS = 'ERROROLDPASS';

export const GETADDRESSES = 'GETADDRESSES';
export const POSTADDRESSES = 'POSTADDRESSES';
export const GETADDRESSESBYID = 'GETADDRESSESBYID';
export const DELETEADDRESSESBYID = 'DELETEADDRESSESBYID';
export const UPDATEADDRESSESBYID = 'UPDATEADDRESSESBYID';
export const UPDATEDEFAULTADDRESS = 'UPDATEDEFAULTADDRESS';

// Avatar
export const GETAVATAR = 'GETAVATAR';
export const POSTAVATAR = 'POSTAVATAR';
export const ERRORAVATAR = 'ERRORAVATAR';

// Products
export const GETPRODUCTS = 'GETPRODUCTS';

//Search
export const GETSEARCH = 'GETSEARCH';

// Cart
export const UPDATECART = 'UPDATECART';
export const UPDATECOUNT = 'UPDATECOUNT';
export const CHECKOUTCART = 'CHECKOUTCART';
export const SETDISCOUNT = 'SETDISCOUNT';

export const GETCARDS = 'GETCARDS';
export const ADDCARD = 'ADDCARD';
export const ERRORCARD = 'ERRORCARD';
export const DEFAULTCARD = 'DEFAULTCARD';
export const REMOVECARD = 'REMOVECARD';

export const PAYMENT = 'PAYMENT';

// Admin
export const GETUSERS = 'GETUSERS';
export const GETCUSTOMPRODUCTS = 'GETCUSTOMPRODUCTS';
export const RESETCUSTOMPRODUCTS = 'RESETCUSTOMPRODUCTS';